# Praktikum 3 - (Sekilas) Seleksi Fitur, Encoding, dan Standardisasi

**Nama:** Radit Firansah  
**NIM:** 244107020196

## Langkah 0 - Persiapan

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler

## Langkah 1 - Load Data

In [2]:
dpath = '../data/Titanic-Dataset-fixed.csv'
df = pd.read_csv(dpath)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,DECK,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,DECK,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,DECK,S

## Langkah 2 - Slice Data

Fitur yang digunakan: `Survived`, `Pclass`, `Age`, `Sex`, `Cabin`.

In [3]:
df = df[['Survived', 'Pclass', 'Age', 'Sex', 'Cabin']].copy()
df.head()

   Survived  Pclass   Age     Sex Cabin
0         0       3  22.0    male  DECK
1         1       1  38.0  female   C85
2         1       3  26.0  female  DECK
3         1       1  35.0  female  C123
4         0       3  35.0    male  DECK

## Langkah 3 - Encoding

Label Encoding pada kolom kategorikal `Sex` dan `Cabin`.

In [4]:
le = LabelEncoder()  # membuat objek dari LabelEncoder
df['Sex'] = le.fit_transform(df['Sex'])  # proses encoding
df['Cabin'] = le.fit_transform(df['Cabin'])  # proses encoding

## Langkah 4 - Verifikasi Hasil

In [5]:
df.head()

   Survived  Pclass   Age  Sex  Cabin
0         0       3  22.0    1    115
1         1       1  38.0    0     81
2         1       3  26.0    0    115
3         1       1  35.0    0     55
4         0       3  35.0    1    115

## Langkah 5 - Standarisasi

Standardisasi pada kolom `Age`.

In [6]:
std = StandardScaler()
df['Age'] = std.fit_transform(df[['Age']])

## Langkah 6 - Verifikasi Hasil Standarisasi

In [7]:
df.head()

   Survived  Pclass       Age  Sex  Cabin
0         0       3 -0.592481    1    115
1         1       1  0.638789    0     81
2         1       3 -0.284663    0    115
3         1       1  0.407926    0     55
4         0       3  0.407926    1    115

In [8]:
df.describe()

         Survived      Pclass           Age         Sex       Cabin
count  891.000000  891.000000  8.910000e+02  891.000000  891.000000
mean     0.383838    2.308642  2.232906e-16    0.647587  106.126824
std      0.486592    0.836071  1.000562e+00    0.477990   26.049018
min      0.000000    1.000000 -2.253155e+00    0.000000    0.000000
25%      0.000000    2.000000 -5.924806e-01    0.000000  115.000000
50%      0.000000    3.000000  0.000000e+00    1.000000  115.000000
75%      1.000000    3.000000  4.079260e-01    1.000000  115.000000
max      1.000000    3.000000  3.870872e+00    1.000000  147.000000